version: "3.3"
services:
    agora-plantuml-server:
        image: plantuml/plantuml-server
        container_name: plantuml-server
        ports:
            - 8080:8080
        environment: 
            PLANTUML_LIMIT_SIZE: 99999 # Limits image width and height
            PLANTUML_STATS: on # Set it to on/off to enable statistics report