name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include: 
    - dev 
pr: none
variables:
  buildConfiguration: 'Release'
  location: 'West US 2'
  azureContainerRegistry: 'plantumlacr1.azurecr.io'
  registryName: 'plantumlacr1'
  resourceGroupName: 'agora-plantuml-server1'
  imageName: 'agora-plantuml-server1'
  webAppName: 'agora-plantuml-server1'
  azureSubscription: 'plantuml-subscription'
  plantUmlStats: $(PLANTUML_STATS)
  plantUmlLimitSize: $(PLANTUML_LIMIT_SIZE)
  dockerfilePath: '**/Dockerfile'

stages:

# Build Stage
- stage: BuildAndTest
  jobs:
  - job: BuildAndTest
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    # Create or update the ACR resource
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment:Create Azure Container Registry'
      inputs:
        azureSubscription: '$(azureSubscription)'
        resourceGroupName: '$(resourceGroupName)'
        location: $(location)
        csmFile: '$(System.DefaultWorkingDirectory)/**/containerRegistry-template.json'
        overrideParameters: '-registryName "$(registryName)" -registryLocation "$(location)" -registrySku standard'       

    # Build container image
    - task: Docker@2
      displayName: 'Build container image'
      inputs:
        azureSubscriptionEndpoint: '$(azureSubscription)'
        azureContainerRegistry: '$(azureContainerRegistry)'
        imageName: '$(imageName):$(Build.BuildId)'
        dockerfile: $(dockerfilePath)
        command: 'build'
        arguments: '--build-arg PLANTUML_STATS=$(plantUmlStats) --build-arg PLANTUML_LIMIT_SIZE=$(plantUmlLimitSize)'

    # Push container image
    - task: Docker@2
      displayName: 'Push container image'
      inputs:
        azureSubscriptionEndpoint: '$(azureSubscription)'
        azureContainerRegistry: '$(azureContainerRegistry)'
        command: 'push'
        imageName: '$(imageName):$(Build.BuildId)'

    # Copy ARM templates
    - task: CopyFiles@2
      displayName: 'Copy ARM templates'
      inputs:
        SourceFolder: '.azure-pipelines/ArmTemplates'
        TargetFolder: '$(build.artifactstagingdirectory)'

    # Publish the app as an artifact
    - publish: $(Build.StagingDirectory)
      artifact: app

# Staging release
- stage: Staging
  jobs:
  - job: Release
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # Don't clone the repo
    - checkout: none

    # Download the published application artifact
    - download: current
      artifact: app

    # Create or update Azure App Service
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment:Create Azure App Service'
      inputs:
        azureSubscription: '$(azureSubscription)'
        resourceGroupName: '$(resourceGroupName)'
        location: '$(location)'
        csmFile: '$(Pipeline.Workspace)/**/container-webapp-template.json'
        overrideParameters: '-webAppName $(webAppName) -hostingPlanName $(webAppName) -appInsightsLocation "$(location)" -sku "S1 Standard" -registryName $(registryName) -registryLocation "$(location)" -registrySku standard -imageName $(imageName):$(Build.BuildId)'

    # Deploy App Service
    - task: AzureRmWebAppDeployment@3
      displayName: 'Deploy Azure App Service'
      inputs:
        azureSubscription: '$(azureSubscription)'
        appType: applinux
        WebAppName: $(webAppName)
        DockerNamespace: $(azureContainerRegistry)
        DockerRepository: $(webAppName)
        DockerImageTag: '$(Build.BuildId)'
        WebAppUri: webAppUrl
        TakeAppOfflineFlag: true
        UseWebDeploy: true
        RenameFilesFlag: true